version: "3.7"

services:

  ## FIXTURE TESTS ##
  breedbase_test_fixture:
    image: triticeaetoolbox/breedbase_web:latest
    container_name: breedbase_test_fixture
    command: "t/unit_fixture/"
    environment:
      PGPASSWORD: postgres
    depends_on:
      breedbase_test_db:
        condition: service_healthy
    healthcheck:
      test: /bin/true
      interval: 60s
    volumes:
      # - ./repos/sgn:/home/production/cxgn/sgn
      - ./entrypoint.sh:/entrypoint.sh
      - ./conf/sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf
      - ./conf/sgn_test.conf:/home/production/cxgn/sgn/sgn_test.conf
      - ./logs_fixture/:/home/production/cxgn/sgn/logs/

  ## MECH TESTS ##
  breedbase_test_mech:
    image: triticeaetoolbox/breedbase_web:latest
    container_name: breedbase_test_mech
    command: "t/unit_mech/"
    environment:
      PGPASSWORD: postgres
    depends_on:
      breedbase_test_db:
        condition: service_healthy
    volumes:
      # - ./repos/sgn:/home/production/cxgn/sgn
      - ./entrypoint.sh:/entrypoint.sh
      - ./conf/sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf
      - ./conf/sgn_test.conf:/home/production/cxgn/sgn/sgn_test.conf
      - ./logs_mech/:/home/production/cxgn/sgn/logs/

  ## SELENIUM TESTS ##
  breedbase_test_selenium:
    image: triticeaetoolbox/breedbase_web:latest
    container_name: breedbase_test_selenium
    command: "t/selenium2/"
    environment:
      PGPASSWORD: postgres
      SGN_REMOTE_SERVER_ADDR: breedbase_test_selenium_server
      SGN_TEST_SERVER: http://breedbase_test_selenium:3010
    depends_on:
      breedbase_test_db:
        condition: service_healthy
      breedbase_test_selenium_server:
        condition: service_healthy
    volumes:
      # - ./repos/sgn:/home/production/cxgn/sgn
      - ./entrypoint.sh:/entrypoint.sh
      - ./conf/sgn_local.conf:/home/production/cxgn/sgn/sgn_local.conf
      - ./conf/sgn_test.conf:/home/production/cxgn/sgn/sgn_test.conf
      - ./logs_selenium/:/home/production/cxgn/sgn/logs/

  breedbase_test_selenium_server:
    image: selenium/standalone-firefox:3.141.59
    container_name: breedbase_test_selenium_server
    healthcheck:
      test: "curl --silent --head http://localhost:4444 || exit 1"

  breedbase_test_db:
    image: postgres:12
    container_name: breedbase_test_db
    shm_size: '1gb'
    healthcheck:
      test: "pg_isready -U postgres || exit 1"
      interval: 10s
    environment: 
      POSTGRES_PASSWORD: postgres